In [1]:
!pip install bs4

Requirement already satisfied: bs4 in c:\users\mones\anaconda3\lib\site-packages (0.0.2)
Requirement already satisfied: beautifulsoup4 in c:\users\mones\anaconda3\lib\site-packages (from bs4) (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\users\mones\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\mones\anaconda3\lib\site-packages (from beautifulsoup4->bs4) (4.15.0)

In [2]:
from bs4 import BeautifulSoup

In [3]:
import numpy as np
import pandas as pd
import re
import requests
import warnings
warnings.filterwarnings('ignore')

In [4]:
url = 'https://www.eazydiner.com/restaurants?location=bengaluru'
headers = {
     "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
}
response = requests.get(url, headers = headers)
response

In [5]:
response.status_code

200

In [6]:
html_code = response.text

In [7]:
soup = BeautifulSoup(html_code)

In [8]:
soup.text[:1000]

'The 20 Best Restaurants in BengaluruJun 2026 | EazyDinerLoginOpen AppYour LocationBengaluruSearch restaurants, locations or cuisinesBe Prime!Contact UsLoginHome /Bengaluru / Top Restaurants in BengaluruBengaluru Restaurants0FiltersSort byPrimeVegBarsLuxury DiningNorth IndianCafe%Flat 20% + 25% with Bank Offers Hamza Express - Since 1918Shivajinagar, Central BengaluruMulticuisine₹650 for two4.0%Flat 10% + 25% with Bank OffersSavera Lassi ShopShivajinagar, Central BengaluruBeverages, Ice Cream₹2000 for two4.7%Flat 10% + 25% with Bank OffersMy BreakfastShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0Ad%Flat 10% + 25% with Bank OffersMasha Allah Hot And Cool PointShivajinagar, Central BengaluruFast Food₹2000 for two4.0%Flat 10% + 25% with Bank OffersNawabi ChaiShivajinagar, Central BengaluruCafe₹200 for two4.0%Flat 10% + 25% with Bank OffersTipsy CafeShivajinagar, Central BengaluruFast Food₹2000 for two4.0AdAdAd%Flat 10% + 25% with Bank OffersShahi RestaurantShivajinagar, Centra'

In [9]:
url = 'https://www.eazydiner.com/restaurants?location=bengaluru&page=236'
for i in range(1,237):
    print(f'https://www.eazydiner.com/restaurants?location=bengaluru&page={i}')

https://www.eazydiner.com/restaurants?location=bengaluru&page=1
https://www.eazydiner.com/restaurants?location=bengaluru&page=2
https://www.eazydiner.com/restaurants?location=bengaluru&page=3
https://www.eazydiner.com/restaurants?location=bengaluru&page=4
https://www.eazydiner.com/restaurants?location=bengaluru&page=5
https://www.eazydiner.com/restaurants?location=bengaluru&page=6
https://www.eazydiner.com/restaurants?location=bengaluru&page=7
https://www.eazydiner.com/restaurants?location=bengaluru&page=8
https://www.eazydiner.com/restaurants?location=bengaluru&page=9
https://www.eazydiner.com/restaurants?location=bengaluru&page=10
https://www.eazydiner.com/restaurants?location=bengaluru&page=11
https://www.eazydiner.com/restaurants?location=bengaluru&page=12
https://www.eazydiner.com/restaurants?location=bengaluru&page=13
https://www.eazydiner.com/restaurants?location=bengaluru&page=14
https://www.eazydiner.com/restaurants?location=bengaluru&page=15
https://www.eazydiner.com/restaurants?location=bengaluru&page=16
https://www.eazydiner.com/restaurants?location=bengaluru&page=17
https://www.eazydiner.com/restaurants?location=bengaluru&page=18
https://www.eazydiner.com/restaurants?location=bengaluru&page=19
https://www.eazydiner.com/restaurants?location=bengaluru&page=20
https://www.eazydiner.com/restaurants?location=bengaluru&page=21
https://www.eazydiner.com/restaurants?location=bengaluru&page=22
https://www.eazydiner.com/restaurants?location=bengaluru&page=23
https://www.eazydiner.com/restaurants?location=bengaluru&page=24
https://www.eazydiner.com/restaurants?location=bengaluru&page=25
https://www.eazydiner.com/restaurants?location=bengaluru&page=26
https://www.eazydiner.com/restaurants?location=bengaluru&page=27
https://www.eazydiner.com/restaurants?location=bengaluru&page=28
https://www.eazydiner.com/restaurants?location=bengaluru&page=29
https://www.eazydiner.com/restaurants?location=bengaluru&page=30
https://www.eazydiner.com/restaurants?location=bengaluru&page=31
https://www.eazydiner.com/restaurants?location=bengaluru&page=32
https://www.eazydiner.com/restaurants?location=bengaluru&page=33
https://www.eazydiner.com/restaurants?location=bengaluru&page=34
https://www.eazydiner.com/restaurants?location=bengaluru&page=35
https://www.eazydiner.com/restaurants?location=bengaluru&page=36
https://www.eazydiner.com/restaurants?location=bengaluru&page=37
https://www.eazydiner.com/restaurants?location=bengaluru&page=38
https://www.eazydiner.com/restaurants?location=bengaluru&page=39
https://www.eazydiner.com/restaurants?location=bengaluru&page=40
https://www.eazydiner.com/restaurants?location=bengaluru&page=41
https://www.eazydiner.com/restaurants?location=bengaluru&page=42
https://www.eazydiner.com/restaurants?location=bengaluru&page=43
https://www.eazydiner.com/restaurants?location=bengaluru&page=44
https://www.eazydiner.com/restaurants?location=bengaluru&page=45
https://www.eazydiner.com/restaurants?location=bengaluru&page=46
https://www.eazydiner.com/restaurants?location=bengaluru&page=47
https://www.eazydiner.com/restaurants?location=bengaluru&page=48
https://www.eazydiner.com/restaurants?location=bengaluru&page=49
https://www.eazydiner.com/restaurants?location=bengaluru&page=50
https://www.eazydiner.com/restaurants?location=bengaluru&page=51
https://www.eazydiner.com/restaurants?location=bengaluru&page=52
https://www.eazydiner.com/restaurants?location=bengaluru&page=53
https://www.eazydiner.com/restaurants?location=bengaluru&page=54
https://www.eazydiner.com/restaurants?location=bengaluru&page=55
https://www.eazydiner.com/restaurants?location=bengaluru&page=56
https://www.eazydiner.com/restaurants?location=bengaluru&page=57
https://www.eazydiner.com/restaurants?location=bengaluru&page=58
https://www.eazydiner.com/restaurants?location=bengaluru&page=59
https://www.eazydiner.com/restaurants?location=bengaluru&page=60
https://www.eazydiner.com/restaurants?location=bengaluru&page=61
https://www.eazydiner.com/restaurants?location=bengaluru&page=62
https://www.eazydiner.com/restaurants?location=bengaluru&page=63
https://www.eazydiner.com/restaurants?location=bengaluru&page=64
https://www.eazydiner.com/restaurants?location=bengaluru&page=65
https://www.eazydiner.com/restaurants?location=bengaluru&page=66
https://www.eazydiner.com/restaurants?location=bengaluru&page=67
https://www.eazydiner.com/restaurants?location=bengaluru&page=68
https://www.eazydiner.com/restaurants?location=bengaluru&page=69
https://www.eazydiner.com/restaurants?location=bengaluru&page=70
https://www.eazydiner.com/restaurants?location=bengaluru&page=71
https://www.eazydiner.com/restaurants?location=bengaluru&page=72
https://www.eazydiner.com/restaurants?location=bengaluru&page=73
https://www.eazydiner.com/restaurants?location=bengaluru&page=74
https://www.eazydiner.com/restaurants?location=bengaluru&page=75
https://www.eazydiner.com/restaurants?location=bengaluru&page=76
https://www.eazydiner.com/restaurants?location=bengaluru&page=77
https://www.eazydiner.com/restaurants?location=bengaluru&page=78
https://www.eazydiner.com/restaurants?location=bengaluru&page=79
https://www.eazydiner.com/restaurants?location=bengaluru&page=80
https://www.eazydiner.com/restaurants?location=bengaluru&page=81
https://www.eazydiner.com/restaurants?location=bengaluru&page=82
https://www.eazydiner.com/restaurants?location=bengaluru&page=83
https://www.eazydiner.com/restaurants?location=bengaluru&page=84
https://www.eazydiner.com/restaurants?location=bengaluru&page=85
https://www.eazydiner.com/restaurants?location=bengaluru&page=86
https://www.eazydiner.com/restaurants?location=bengaluru&page=87
https://www.eazydiner.com/restaurants?location=bengaluru&page=88
https://www.eazydiner.com/restaurants?location=bengaluru&page=89
https://www.eazydiner.com/restaurants?location=bengaluru&page=90
https://www.eazydiner.com/restaurants?location=bengaluru&page=91
https://www.eazydiner.com/restaurants?location=bengaluru&page=92
https://www.eazydiner.com/restaurants?location=bengaluru&page=93
https://www.eazydiner.com/restaurants?location=bengaluru&page=94
https://www.eazydiner.com/restaurants?location=bengaluru&page=95
https://www.eazydiner.com/restaurants?location=bengaluru&page=96
https://www.eazydiner.com/restaurants?location=bengaluru&page=97
https://www.eazydiner.com/restaurants?location=bengaluru&page=98
https://www.eazydiner.com/restaurants?location=bengaluru&page=99
https://www.eazydiner.com/restaurants?location=bengaluru&page=100
https://www.eazydiner.com/restaurants?location=bengaluru&page=101
https://www.eazydiner.com/restaurants?location=bengaluru&page=102
https://www.eazydiner.com/restaurants?location=bengaluru&page=103
https://www.eazydiner.com/restaurants?location=bengaluru&page=104
https://www.eazydiner.com/restaurants?location=bengaluru&page=105
https://www.eazydiner.com/restaurants?location=bengaluru&page=106
https://www.eazydiner.com/restaurants?location=bengaluru&page=107
https://www.eazydiner.com/restaurants?location=bengaluru&page=108
https://www.eazydiner.com/restaurants?location=bengaluru&page=109
https://www.eazydiner.com/restaurants?location=bengaluru&page=110
https://www.eazydiner.com/restaurants?location=bengaluru&page=111
https://www.eazydiner.com/restaurants?location=bengaluru&page=112
https://www.eazydiner.com/restaurants?location=bengaluru&page=113
https://www.eazydiner.com/restaurants?location=bengaluru&page=114
https://www.eazydiner.com/restaurants?location=bengaluru&page=115
https://www.eazydiner.com/restaurants?location=bengaluru&page=116
https://www.eazydiner.com/restaurants?location=bengaluru&page=117
https://www.eazydiner.com/restaurants?location=bengaluru&page=118
https://www.eazydiner.com/restaurants?location=bengaluru&page=119
https://www.eazydiner.com/restaurants?location=bengaluru&page=120
https://www.eazydiner.com/restaurants?location=bengaluru&page=121
https://www.eazydiner.com/restaurants?location=bengaluru&page=122
https://www.eazydiner.com/restaurants?location=bengaluru&page=123
https://www.eazydiner.com/restaurants?location=bengaluru&page=124
https://www.eazydiner.com/restaurants?location=bengaluru&page=125
https://www.eazydiner.com/restaurants?location=bengaluru&page=126
https://www.eazydiner.com/restaurants?location=bengaluru&page=127
https://www.eazydiner.com/restaurants?location=bengaluru&page=128
https://www.eazydiner.com/restaurants?location=bengaluru&page=129
https://www.eazydiner.com/restaurants?location=bengaluru&page=130
https://www.eazydiner.com/restaurants?location=bengaluru&page=131
https://www.eazydiner.com/restaurants?location=bengaluru&page=132
https://www.eazydiner.com/restaurants?location=bengaluru&page=133
https://www.eazydiner.com/restaurants?location=bengaluru&page=134
https://www.eazydiner.com/restaurants?location=bengaluru&page=135
https://www.eazydiner.com/restaurants?location=bengaluru&page=136
https://www.eazydiner.com/restaurants?location=bengaluru&page=137
https://www.eazydiner.com/restaurants?location=bengaluru&page=138
https://www.eazydiner.com/restaurants?location=bengaluru&page=139
https://www.eazydiner.com/restaurants?location=bengaluru&page=140
https://www.eazydiner.com/restaurants?location=bengaluru&page=141
https://www.eazydiner.com/restaurants?location=bengaluru&page=142
https://www.eazydiner.com/restaurants?location=bengaluru&page=143
https://www.eazydiner.com/restaurants?location=bengaluru&page=144
https://www.eazydiner.com/restaurants?location=bengaluru&page=145
https://www.eazydiner.com/restaurants?location=bengaluru&page=146
https://www.eazydiner.com/restaurants?location=bengaluru&page=147
https://www.eazydiner.com/restaurants?location=bengaluru&page=148
https://www.eazydiner.com/restaurants?location=bengaluru&page=149
https://www.eazydiner.com/restaurants?location=bengaluru&page=150
https://www.eazydiner.com/restaurants?location=bengaluru&page=151
https://www.eazydiner.com/restaurants?location=bengaluru&page=152
https://www.eazydiner.com/restaurants?location=bengaluru&page=153
https://www.eazydiner.com/restaurants?location=bengaluru&page=154
https://www.eazydiner.com/restaurants?location=bengaluru&page=155
https://www.eazydiner.com/restaurants?location=bengaluru&page=156
https://www.eazydiner.com/restaurants?location=bengaluru&page=157
https://www.eazydiner.com/restaurants?location=bengaluru&page=158
https://www.eazydiner.com/restaurants?location=bengaluru&page=159
https://www.eazydiner.com/restaurants?location=bengaluru&page=160
https://www.eazydiner.com/restaurants?location=bengaluru&page=161
https://www.eazydiner.com/restaurants?location=bengaluru&page=162
https://www.eazydiner.com/restaurants?location=bengaluru&page=163
https://www.eazydiner.com/restaurants?location=bengaluru&page=164
https://www.eazydiner.com/restaurants?location=bengaluru&page=165
https://www.eazydiner.com/restaurants?location=bengaluru&page=166
https://www.eazydiner.com/restaurants?location=bengaluru&page=167
https://www.eazydiner.com/restaurants?location=bengaluru&page=168
https://www.eazydiner.com/restaurants?location=bengaluru&page=169
https://www.eazydiner.com/restaurants?location=bengaluru&page=170
https://www.eazydiner.com/restaurants?location=bengaluru&page=171
https://www.eazydiner.com/restaurants?location=bengaluru&page=172
https://www.eazydiner.com/restaurants?location=bengaluru&page=173
https://www.eazydiner.com/restaurants?location=bengaluru&page=174
https://www.eazydiner.com/restaurants?location=bengaluru&page=175
https://www.eazydiner.com/restaurants?location=bengaluru&page=176
https://www.eazydiner.com/restaurants?location=bengaluru&page=177
https://www.eazydiner.com/restaurants?location=bengaluru&page=178
https://www.eazydiner.com/restaurants?location=bengaluru&page=179
https://www.eazydiner.com/restaurants?location=bengaluru&page=180
https://www.eazydiner.com/restaurants?location=bengaluru&page=181
https://www.eazydiner.com/restaurants?location=bengaluru&page=182
https://www.eazydiner.com/restaurants?location=bengaluru&page=183
https://www.eazydiner.com/restaurants?location=bengaluru&page=184
https://www.eazydiner.com/restaurants?location=bengaluru&page=185
https://www.eazydiner.com/restaurants?location=bengaluru&page=186
https://www.eazydiner.com/restaurants?location=bengaluru&page=187
https://www.eazydiner.com/restaurants?location=bengaluru&page=188
https://www.eazydiner.com/restaurants?location=bengaluru&page=189
https://www.eazydiner.com/restaurants?location=bengaluru&page=190
https://www.eazydiner.com/restaurants?location=bengaluru&page=191
https://www.eazydiner.com/restaurants?location=bengaluru&page=192
https://www.eazydiner.com/restaurants?location=bengaluru&page=193
https://www.eazydiner.com/restaurants?location=bengaluru&page=194
https://www.eazydiner.com/restaurants?location=bengaluru&page=195
https://www.eazydiner.com/restaurants?location=bengaluru&page=196
https://www.eazydiner.com/restaurants?location=bengaluru&page=197
https://www.eazydiner.com/restaurants?location=bengaluru&page=198
https://www.eazydiner.com/restaurants?location=bengaluru&page=199
https://www.eazydiner.com/restaurants?location=bengaluru&page=200
https://www.eazydiner.com/restaurants?location=bengaluru&page=201
https://www.eazydiner.com/restaurants?location=bengaluru&page=202
https://www.eazydiner.com/restaurants?location=bengaluru&page=203
https://www.eazydiner.com/restaurants?location=bengaluru&page=204
https://www.eazydiner.com/restaurants?location=bengaluru&page=205
https://www.eazydiner.com/restaurants?location=bengaluru&page=206
https://www.eazydiner.com/restaurants?location=bengaluru&page=207
https://www.eazydiner.com/restaurants?location=bengaluru&page=208
https://www.eazydiner.com/restaurants?location=bengaluru&page=209
https://www.eazydiner.com/restaurants?location=bengaluru&page=210
https://www.eazydiner.com/restaurants?location=bengaluru&page=211
https://www.eazydiner.com/restaurants?location=bengaluru&page=212
https://www.eazydiner.com/restaurants?location=bengaluru&page=213
https://www.eazydiner.com/restaurants?location=bengaluru&page=214
https://www.eazydiner.com/restaurants?location=bengaluru&page=215
https://www.eazydiner.com/restaurants?location=bengaluru&page=216
https://www.eazydiner.com/restaurants?location=bengaluru&page=217
https://www.eazydiner.com/restaurants?location=bengaluru&page=218
https://www.eazydiner.com/restaurants?location=bengaluru&page=219
https://www.eazydiner.com/restaurants?location=bengaluru&page=220
https://www.eazydiner.com/restaurants?location=bengaluru&page=221
https://www.eazydiner.com/restaurants?location=bengaluru&page=222
https://www.eazydiner.com/restaurants?location=bengaluru&page=223
https://www.eazydiner.com/restaurants?location=bengaluru&page=224
https://www.eazydiner.com/restaurants?location=bengaluru&page=225
https://www.eazydiner.com/restaurants?location=bengaluru&page=226
https://www.eazydiner.com/restaurants?location=bengaluru&page=227
https://www.eazydiner.com/restaurants?location=bengaluru&page=228
https://www.eazydiner.com/restaurants?location=bengaluru&page=229
https://www.eazydiner.com/restaurants?location=bengaluru&page=230
https://www.eazydiner.com/restaurants?location=bengaluru&page=231
https://www.eazydiner.com/restaurants?location=bengaluru&page=232
https://www.eazydiner.com/restaurants?location=bengaluru&page=233
https://www.eazydiner.com/restaurants?location=bengaluru&page=234
https://www.eazydiner.com/restaurants?location=bengaluru&page=235
https://www.eazydiner.com/restaurants?location=bengaluru&page=236

In [10]:
restaurants = soup.find('h3', attrs = {'class': 'margin-0-auto all_unset'})
restaurants.text

' Hamza Express - Since 1918'

In [11]:
price = soup.find("div", attrs = {"class": "flex align-v-center gap_5 relative"})
price.text

'Multicuisine₹650 for two'

In [12]:
area = soup.find("div", attrs = {"class": "flex align-v-center gap_5 padding relative"})
area.text

'Shivajinagar, Central Bengaluru'

In [13]:
rating = soup.find("div", attrs = {"class": "flex align-v-start flex-between padding-t-15 padding-b-15 margin-t-12 relative full-width"})
rating.text

' Hamza Express - Since 1918Shivajinagar, Central BengaluruMulticuisine₹650 for two4.0'

In [14]:
discount = soup.find('div', attrs = {"class": "relative font-16 bold white nowrap ellipsis"})
discount.text

'Flat 20% + 25% with Bank Offers'

In [15]:
restaurants = soup.find_all('h3', attrs = {'class': 'margin-0-auto all_unset'})
len(restaurants)

87

In [16]:
location = soup.find_all("div", attrs = {"class": "flex align-v-start flex-between padding-t-15 padding-b-15 margin-t-12 relative full-width"})
len(location)

9

In [17]:
restaurants_name = []
prices = []
area = []
reatings = []
discounts = []

for i in range(1,151):
    url = f'https://www.eazydiner.com/bengaluru/restaurants?page={i}'
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36"
    }
    response = requests.get(url, headers = headers)
    html_code = response.text
    soup = BeautifulSoup(html_code,'html.parser')
    container = soup.find_all('div', attrs = {'class': 'relative pointer'})

    for c in container:
        # package Name
        restaurants = c.find('h3', attrs = {'class': 'margin-0-auto all_unset'})
        if restaurants is None:
            restaurants_name.append(np.nan)
        else:
            restaurants_name.append(restaurants.text)

        # duration
        pri = c.find('div', attrs = {'class': 'flex align-v-center gap_5 relative'})
        if pri is None:
            prices.append(np.nan)
        else:
            prices.append(pri.text)

        # Area 
        loc = c.find('div', attrs = {'class': 'flex align-v-center gap_5 padding relative'})
        if loc is None:
            area.append(np.nan)
        else:
            area.append(loc.text)

        # details 
        rating = c.find('div', attrs = {'class': 'flex align-v-start flex-between padding-t-15 padding-b-15 margin-t-12 relative full-width'})
        if rating is None:
            reatings.append(np.nan)
        else:
            reatings.append(rating.text)
            
        #package price
        discount = c.find('div', attrs = {'class': 'relative font-16 bold white nowrap ellipsis'})
        if discount is None:
            discounts.append(np.nan)
        else:
            discounts.append(discount.text)

In [18]:
print(container[0].find('h3', attrs = {'class':'margin-0-auto all_unset'}).text)
print(container[0].find('div', attrs = {'class':'flex align-v-center gap_5 relative'}).text)
print(container[0].find('div', attrs = {'class':'flex align-v-center gap_5 padding relative'}).text)
print(container[0].find('div', attrs = {'class':'flex align-v-start flex-between padding-t-15 padding-b-15 margin-t-12 relative full-width'}).text)
print(container[0].find('div', attrs = {'class':'relative font-16 bold white nowrap ellipsis'}).text)

Flavours Of Andhra
Indian₹1000 for two
Marathahalli, East Bengaluru
Flavours Of AndhraMarathahalli, East BengaluruIndian₹1000 for two4.1
Flat 10% + 25% with Bank Offers

In [19]:
print("restaurants_name: ", len(restaurants_name))
print("prices: ", len(prices))
print("area: ", len(area))
print("reatings: ", len(reatings))
print("discounts: ", len(discounts))

restaurants_name:  2400
prices:  2400
area:  2400
reatings:  2400
discounts:  2400

In [32]:
df = pd.DataFrame({
    "Restaurants_Name" : restaurants_name,
    "Cost_of_two" : prices,
    "Areas" : area,
    "Reatings" : reatings,
    "Discounts" : discounts
})
df

,Restaurants_Name,Cost_of_two,Areas,Reatings,Discounts
0,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers
1,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers
2,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers
3,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers
4,My Breakfast,Multicuisine₹2000 for two,"Shivajinagar, Central Bengaluru","My BreakfastShivajinagar, Central BengaluruMul...",Flat 10% + 25% with Bank Offers
...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine₹2500 for two,"Yelahanka, North Bengaluru","The Brew Factory Sahakara NagarYelahanka, Nort...",25% Off :Payeazy
2396,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers
2397,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers
2398,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers
2399,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers

In [33]:
df.to_csv('eazydiner_webscraping_dataset.csv',index = False)

In [58]:
df = pd.read_csv('eazydiner_webscraping_dataset.csv')
df

,Restaurants_Name,Cost_of_two,Areas,Reatings,Discounts
0,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers
1,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers
2,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers
3,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers
4,My Breakfast,Multicuisine₹2000 for two,"Shivajinagar, Central Bengaluru","My BreakfastShivajinagar, Central BengaluruMul...",Flat 10% + 25% with Bank Offers
...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine₹2500 for two,"Yelahanka, North Bengaluru","The Brew Factory Sahakara NagarYelahanka, Nort...",25% Off :Payeazy
2396,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers
2397,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers
2398,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers
2399,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers

In [59]:
data_lines = df.values.tolist()
print(data_lines)

[[' Hamza Express - Since 1918', 'Multicuisine₹650 for two', 'Shivajinagar, Central Bengaluru', ' Hamza Express - Since 1918Shivajinagar, Central BengaluruMulticuisine₹650 for two4.0', 'Flat 10% + 25% with Bank Offers'], [' Hamza Express - Since 1918', 'Multicuisine₹650 for two', 'Shivajinagar, Central Bengaluru', ' Hamza Express - Since 1918Shivajinagar, Central BengaluruMulticuisine₹650 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Savera Lassi Shop', 'Beverages, Ice Cream₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Savera Lassi ShopShivajinagar, Central BengaluruBeverages, Ice Cream₹2000 for two4.7', 'Flat 10% + 25% with Bank Offers'], ['Savera Lassi Shop', 'Beverages, Ice Cream₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Savera Lassi ShopShivajinagar, Central BengaluruBeverages, Ice Cream₹2000 for two4.7', 'Flat 10% + 25% with Bank Offers'], ['My Breakfast', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'My BreakfastShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['My Breakfast', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'My BreakfastShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Nawabi Chai', 'Cafe₹200 for two', 'Shivajinagar, Central Bengaluru', 'Nawabi ChaiShivajinagar, Central BengaluruCafe₹200 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Nawabi Chai', 'Cafe₹200 for two', 'Shivajinagar, Central Bengaluru', 'Nawabi ChaiShivajinagar, Central BengaluruCafe₹200 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Tipsy Cafe', 'Fast Food₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Tipsy CafeShivajinagar, Central BengaluruFast Food₹2000 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Tipsy Cafe', 'Fast Food₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Tipsy CafeShivajinagar, Central BengaluruFast Food₹2000 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Shahi Restaurant', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Shahi RestaurantShivajinagar, Central BengaluruMulticuisine₹2000 for two3.0', 'Flat 10% + 25% with Bank Offers'], ['Shahi Restaurant', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Shahi RestaurantShivajinagar, Central BengaluruMulticuisine₹2000 for two3.0', 'Flat 10% + 25% with Bank Offers'], ['Main Lassi Shop', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Main Lassi ShopShivajinagar, Central BengaluruMulticuisine₹2000 for two1.0', 'Flat 10% + 25% with Bank Offers'], ['Main Lassi Shop', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Main Lassi ShopShivajinagar, Central BengaluruMulticuisine₹2000 for two1.0', 'Flat 10% + 25% with Bank Offers'], ['Maggi Baba', 'Beverages₹200 for two', 'Shivajinagar, Central Bengaluru', 'Maggi BabaShivajinagar, Central BengaluruBeverages₹200 for two5.0', '25% Off :Payeazy'], ['Maggi Baba', 'Beverages₹200 for two', 'Shivajinagar, Central Bengaluru', 'Maggi BabaShivajinagar, Central BengaluruBeverages₹200 for two5.0', '25% Off :Payeazy'], ['Romeo Cafe', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Romeo CafeShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0', '25% Off :Payeazy'], ['Romeo Cafe', 'Multicuisine₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Romeo CafeShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0', '25% Off :Payeazy'], ['CBD Central Bar District', 'Multicuisine₹1200 for two', 'MSR Nagar, Bengaluru', 'CBD Central Bar DistrictMSR Nagar, BengaluruMulticuisine₹1200 for two4.8', 'Flat 25% + 25% with Bank Offers'], ['CBD Central Bar District', 'Multicuisine₹1200 for two', 'MSR Nagar, Bengaluru', 'CBD Central Bar DistrictMSR Nagar, BengaluruMulticuisine₹1200 for two4.8', 'Flat 25% + 25% with Bank Offers'], ['Flo', 'Multicuisine, Cocktail Menu₹2000 for two', 'Church Street, Central Bengaluru', 'FloChurch Street, Central BengaluruMulticuisine, Cocktail Menu₹2000 for two3.3', 'Flat 30% + 25% with Bank Offers'], ['Flo', 'Multicuisine, Cocktail Menu₹2000 for two', 'Church Street, Central Bengaluru', 'FloChurch Street, Central BengaluruMulticuisine, Cocktail Menu₹2000 for two3.3', 'Flat 30% + 25% with Bank Offers'], ['ShakesBierre', 'Cocktail Menu, Multicuisine₹2000 for two', 'MG Road, Central Bengaluru', 'ShakesBierreMG Road, Central BengaluruCocktail Menu, Multicuisine₹2000 for two4.4', 'Flat 10% + 25% with Bank Offers'], ['ShakesBierre', 'Cocktail Menu, Multicuisine₹2000 for two', 'MG Road, Central Bengaluru', 'ShakesBierreMG Road, Central BengaluruCocktail Menu, Multicuisine₹2000 for two4.4', 'Flat 10% + 25% with Bank Offers'], ['Paradox Pub', 'Chinese, Finger Food, Continental₹1200 for two', 'Ashok Nagar, Bengaluru', 'Paradox PubAshok Nagar, BengaluruChinese, Finger Food, Continental₹1200 for two5.0', 'Flat 30% + 25% with Bank Offers'], ['Paradox Pub', 'Chinese, Finger Food, Continental₹1200 for two', 'Ashok Nagar, Bengaluru', 'Paradox PubAshok Nagar, BengaluruChinese, Finger Food, Continental₹1200 for two5.0', 'Flat 30% + 25% with Bank Offers'], ['Navya Samrat Restaurant', 'Multicuisine₹2500 for two', 'Infantry Road, Central Bengaluru', 'Navya Samrat RestaurantInfantry Road, Central BengaluruMulticuisine₹2500 for two5.0', 'Flat 10% + 25% with Bank Offers'], ['Navya Samrat Restaurant', 'Multicuisine₹2500 for two', 'Infantry Road, Central Bengaluru', 'Navya Samrat RestaurantInfantry Road, Central BengaluruMulticuisine₹2500 for two5.0', 'Flat 10% + 25% with Bank Offers'], ['Coastal Machali Co.', 'Indian Coastal Cuisine, Chinese₹1500 for two', 'Residency Road, Central Bengaluru', 'Coastal Machali Co.Residency Road, Central BengaluruIndian Coastal Cuisine, Chinese₹1500 for two4.6', 'Flat 15% + 25% with Bank Offers'], ['Coastal Machali Co.', 'Indian Coastal Cuisine, Chinese₹1500 for two', 'Residency Road, Central Bengaluru', 'Coastal Machali Co.Residency Road, Central BengaluruIndian Coastal Cuisine, Chinese₹1500 for two4.6', 'Flat 15% + 25% with Bank Offers'], ['SMOOR', 'European₹2000 for two', 'Lavelle Road, Central Bengaluru\xa0 | View All(9) Outlets', 'SMOORLavelle Road, Central Bengaluru\xa0 | View All(9) OutletsEuropean₹2000 for two4.6', 'Flat 10% + 25% with Bank Offers'], ['SMOOR', 'European₹2000 for two', 'Lavelle Road, Central Bengaluru\xa0 | View All(9) Outlets', 'SMOORLavelle Road, Central Bengaluru\xa0 | View All(9) OutletsEuropean₹2000 for two4.6', 'Flat 10% + 25% with Bank Offers'], ['Rolls On Wheels', 'Chinese, Fast Food₹500 for two', 'Cunningham Road, Central Bengaluru\xa0 | View All(19) Outlets', 'Rolls On WheelsCunningham Road, Central Bengaluru\xa0 | View All(19) OutletsChinese, Fast Food₹500 for two4.0', 'Flat 15% + 25% with Bank Offers'], ['Rolls On Wheels', 'Chinese, Fast Food₹500 for two', 'Cunningham Road, Central Bengaluru\xa0 | View All(19) Outlets', 'Rolls On WheelsCunningham Road, Central Bengaluru\xa0 | View All(19) OutletsChinese, Fast Food₹500 for two4.0', 'Flat 15% + 25% with Bank Offers'], ['Hatti Kaapi', 'Multicuisine₹400 for two', 'Infantry Road, Central Bengaluru\xa0 | View All(15) Outlets', 'Hatti KaapiInfantry Road, Central Bengaluru\xa0 | View All(15) OutletsMulticuisine₹400 for two5.0', 'Flat 10% + 25% with Bank Offers'], ['Hatti Kaapi', 'Multicuisine₹400 for two', 'Infantry Road, Central Bengaluru\xa0 | View All(15) Outlets', 'Hatti KaapiInfantry Road, Central Bengaluru\xa0 | View All(15) OutletsMulticuisine₹400 for two5.0', 'Flat 10% + 25% with Bank Offers'], ['Tiamo', 'Italian, Mediterranean₹3000 for two', 'Conrad Bengaluru', 'TiamoConrad BengaluruItalian, Mediterranean₹3000 for two4.4', 'Flat 15% + 25% with Bank Offers'], ['Tiamo', 'Italian, Mediterranean₹3000 for two', 'Conrad Bengaluru', 'TiamoConrad BengaluruItalian, Mediterranean₹3000 for two4.4', 'Flat 15% + 25% with Bank Offers'], ['Punjab Grill', 'North Indian₹2000 for two', 'Ashok Nagar, Bengaluru\xa0 | View All(8) Outlets', 'Punjab GrillAshok Nagar, Bengaluru\xa0 | View All(8) OutletsNorth Indian₹2000 for two4.2', 'Flat 15% + 25% with Bank Offers'], ['Punjab Grill', 'North Indian₹2000 for two', 'Ashok Nagar, Bengaluru\xa0 | View All(8) Outlets', 'Punjab GrillAshok Nagar, Bengaluru\xa0 | View All(8) OutletsNorth Indian₹2000 for two4.2', 'Flat 15% + 25% with Bank Offers'], ['Alchemy', 'Fusion, Indian₹2500 for two', 'The Chancery Pavilion, Bengaluru', 'AlchemyThe Chancery Pavilion, BengaluruFusion, Indian₹2500 for two4.5', 'Flat 10% + 25% with Bank Offers'], ['Alchemy', 'Fusion, Indian₹2500 for two', 'The Chancery Pavilion, Bengaluru', 'AlchemyThe Chancery Pavilion, BengaluruFusion, Indian₹2500 for two4.5', 'Flat 10% + 25% with Bank Offers'], ['JW Kitchen', 'Multicuisine₹2500 for two', 'JW Marriott, Bengaluru, Central Bengaluru', 'JW KitchenJW Marriott, Bengaluru, Central BengaluruMulticuisine₹2500 for two4.4', 'Flat 25% + 25% with Bank Offers'], ['JW Kitchen', 'Multicuisine₹2500 for two', 'JW Marriott, Bengaluru, Central Bengaluru', 'JW KitchenJW Marriott, Bengaluru, Central BengaluruMulticuisine₹2500 for two4.4', 'Flat 25% + 25% with Bank Offers'], ['Maayaa', 'South Indian₹2000 for two', 'The Courtyard by Sublime, Bengaluru', 'MaayaaThe Courtyard by Sublime, BengaluruSouth Indian₹2000 for two4.4', 'Flat 15% + 25% with Bank Offers'], ['Maayaa', 'South Indian₹2000 for two', 'The Courtyard by Sublime, Bengaluru', 'MaayaaThe Courtyard by Sublime, BengaluruSouth Indian₹2000 for two4.4', 'Flat 15% + 25% with Bank Offers'], ['Purpose Matcha + Coffee House', 'Coffee₹550 for two', 'Ashok Nagar, Bengaluru', 'Purpose Matcha + Coffee HouseAshok Nagar, BengaluruCoffee₹550 for two4.7', '25% Off :Payeazy'], ['Purpose Matcha + Coffee House', 'Coffee₹550 for two', 'Ashok Nagar, Bengaluru', 'Purpose Matcha + Coffee HouseAshok Nagar, BengaluruCoffee₹550 for two4.7', '25% Off :Payeazy'], ['Muro India', 'Thai, Cantonese₹5000 for two', 'Museum Road, Ashok Nagar, Bengaluru', 'Muro IndiaMuseum Road, Ashok Nagar, BengaluruThai, Cantonese₹5000 for two4.5', '25% Off :Payeazy'], ['Muro India', 'Thai, Cantonese₹5000 for two', 'Museum Road, Ashok Nagar, Bengaluru', 'Muro IndiaMuseum Road, Ashok Nagar, BengaluruThai, Cantonese₹5000 for two4.5', '25% Off :Payeazy'], ['Zed The Baker', 'Italian, French₹2000 for two', 'Church Street, Central Bengaluru\xa0 | View All(5) Outlets', 'Zed The BakerChurch Street, Central Bengaluru\xa0 | View All(5) OutletsItalian, French₹2000 for two4.5', 'Flat 10% + 25% with Bank Offers'], ['Zed The Baker', 'Italian, French₹2000 for two', 'Church Street, Central Bengaluru\xa0 | View All(5) Outlets', 'Zed The BakerChurch Street, Central Bengaluru\xa0 | View All(5) OutletsItalian, French₹2000 for two4.5', 'Flat 10% + 25% with Bank Offers'], ['Yauatcha', 'Multicuisine₹3000 for two', '1MG Road Mall, MG Road', 'Yauatcha1MG Road Mall, MG RoadMulticuisine₹3000 for two4.6', '25% Off :Payeazy'], ['Yauatcha', 'Multicuisine₹3000 for two', '1MG Road Mall, MG Road', 'Yauatcha1MG Road Mall, MG RoadMulticuisine₹3000 for two4.6', '25% Off :Payeazy'], ['Spice It', 'Multicuisine₹2000 for two', 'Ibis Hotel, Richmond Road\xa0 | View All(4) Outlets', 'Spice ItIbis Hotel, Richmond Road\xa0 | View All(4) OutletsMulticuisine₹2000 for two3.5', 'Flat 30% + 25% with Bank Offers'], ['Spice It', 'Multicuisine₹2000 for two', 'Ibis Hotel, Richmond Road\xa0 | View All(4) Outlets', 'Spice ItIbis Hotel, Richmond Road\xa0 | View All(4) OutletsMulticuisine₹2000 for two3.5', 'Flat 30% + 25% with Bank Offers'], ['Scottish Pub', 'Multicuisine₹2000 for two', 'St. Marks Road, Central Bengaluru', 'Scottish PubSt. Marks Road, Central BengaluruMulticuisine₹2000 for two4.9', 'Flat 10% + 25% with Bank Offers'], ['Scottish Pub', 'Multicuisine₹2000 for two', 'St. Marks Road, Central Bengaluru', 'Scottish PubSt. Marks Road, Central BengaluruMulticuisine₹2000 for two4.9', 'Flat 10% + 25% with Bank Offers'], ['Monsoon', 'Multicuisine₹2000 for two', 'The Park, Bengaluru', 'MonsoonThe Park, BengaluruMulticuisine₹2000 for two3.9', 'Flat 25% + 25% with Bank Offers'], ['Monsoon', 'Multicuisine₹2000 for two', 'The Park, Bengaluru', 'MonsoonThe Park, BengaluruMulticuisine₹2000 for two3.9', 'Flat 25% + 25% with Bank Offers'], ['Church Street Social', 'Multicuisine₹2000 for two', 'Church Street, Central Bengaluru\xa0 | View All(12) Outlets', 'Church Street SocialChurch Street, Central Bengaluru\xa0 | View All(12) OutletsMulticuisine₹2000 for two4.2', '25% Off :Payeazy'], ['Church Street Social', 'Multicuisine₹2000 for two', 'Church Street, Central Bengaluru\xa0 | View All(12) Outlets', 'Church Street SocialChurch Street, Central Bengaluru\xa0 | View All(12) OutletsMulticuisine₹2000 for two4.2', '25% Off :Payeazy'], ['Toca Terrace', 'Multicuisine₹2000 for two', 'Brigade Road, Central Bengaluru', 'Toca TerraceBrigade Road, Central BengaluruMulticuisine₹2000 for two4.0', '25% Off :Payeazy'], ['Toca Terrace', 'Multicuisine₹2000 for two', 'Brigade Road, Central Bengaluru', 'Toca TerraceBrigade Road, Central BengaluruMulticuisine₹2000 for two4.0', '25% Off :Payeazy'], ["SkyDeck By Sherlock's", 'Multicuisine₹2000 for two', 'MG Road, Central Bengaluru', "SkyDeck By Sherlock'sMG Road, Central BengaluruMulticuisine₹2000 for two4.1", 'Flat 15% + 25% with Bank Offers'], ["SkyDeck By Sherlock's", 'Multicuisine₹2000 for two', 'MG Road, Central Bengaluru', "SkyDeck By Sherlock'sMG Road, Central BengaluruMulticuisine₹2000 for two4.1", 'Flat 15% + 25% with Bank Offers'], ['Ishaara', 'Multicuisine₹1800 for two', 'St. Marks Road, Central Bengaluru', 'IshaaraSt. Marks Road, Central BengaluruMulticuisine₹1800 for two5.0', 'Flat 10% + 25% with Bank Offers'], ['Ishaara', 'Multicuisine₹1800 for two', 'St. Marks Road, Central Bengaluru', 'IshaaraSt. Marks Road, Central BengaluruMulticuisine₹1800 for two5.0', 'Flat 10% + 25% with Bank Offers'], ["Ta'aam", 'Arabian, North Indian₹600 for two', 'Cunningham Road, Central Bengaluru', "Ta'aamCunningham Road, Central BengaluruArabian, North Indian₹600 for two5.0", '25% Off :Payeazy'], ["Ta'aam", 'Arabian, North Indian₹600 for two', 'Cunningham Road, Central Bengaluru', "Ta'aamCunningham Road, Central BengaluruArabian, North Indian₹600 for two5.0", '25% Off :Payeazy'], ['Cafe Noir', 'European₹1000 for two', 'UB City, Central Bengaluru\xa0 | View All(6) Outlets', 'Cafe NoirUB City, Central Bengaluru\xa0 | View All(6) OutletsEuropean₹1000 for two4.4', 'Flat 10% + 25% with Bank Offers'], ['Cafe Noir', 'European₹1000 for two', 'UB City, Central Bengaluru\xa0 | View All(6) Outlets', 'Cafe NoirUB City, Central Bengaluru\xa0 | View All(6) OutletsEuropean₹1000 for two4.4', 'Flat 10% + 25% with Bank Offers'], ['Sable Cafe', 'Desserts, European, Cafe₹600 for two', 'Indiranagar, East Bengaluru', 'Sable CafeIndiranagar, East BengaluruDesserts, European, Cafe₹600 for two4.0', 'Flat 15% + 25% with Bank Offers'], ['Sable Cafe', 'Desserts, European, Cafe₹600 for two', 'Indiranagar, East Bengaluru', 'Sable CafeIndiranagar, East BengaluruDesserts, European, Cafe₹600 for two4.0', 'Flat 15% + 25% with Bank Offers'], ['New Kudla Family Restaurant', 'North Indian, Chinese₹2000 for two', 'MG Road, Central Bengaluru', 'New Kudla Family RestaurantMG Road, Central BengaluruNorth Indian, Chinese₹2000 for two4.0', 'Flat 50% + 25% with Bank Offers'], ['New Kudla Family Restaurant', 'North Indian, Chinese₹2000 for two', 'MG Road, Central Bengaluru', 'New Kudla Family RestaurantMG Road, Central BengaluruNorth Indian, Chinese₹2000 for two4.0', 'Flat 50% + 25% with Bank Offers'], ['Monarch Cafe', 'Multicuisine₹2000 for two', 'Infantry Road, Central Bengaluru', 'Monarch CafeInfantry Road, Central BengaluruMulticuisine₹2000 for two4.0', '25% Off :Payeazy'], ['Monarch Cafe', 'Multicuisine₹2000 for two', 'Infantry Road, Central Bengaluru', 'Monarch CafeInfantry Road, Central BengaluruMulticuisine₹2000 for two4.0', '25% Off :Payeazy'], ['Cafe Adams', 'European₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Cafe AdamsShivajinagar, Central BengaluruEuropean₹2000 for two4.0', '25% Off :Payeazy'], ['Cafe Adams', 'European₹2000 for two', 'Shivajinagar, Central Bengaluru', 'Cafe AdamsShivajinagar, Central BengaluruEuropean₹2000 for two4.0', '25% Off :Payeazy'], ['Atlas World Cafe', 'Multicuisine₹2000 for two', 'Vividus Hotel, Bengaluru', 'Atlas World CafeVividus Hotel, BengaluruMulticuisine₹2000 for two4.2', 'Flat 15% + 25% with Bank Offers'], ['Atlas World Cafe', 'Multicuisine₹2000 for two', 'Vividus Hotel, Bengaluru', 'Atlas World CafeVividus Hotel, BengaluruMulticuisine₹2000 for two4.2', 'Flat 15% + 25% with Bank Offers'], ['Chianti', 'Multicuisine₹2000 for two', 'MG Road, Central Bengaluru\xa0 | View All(7) Outlets', 'ChiantiMG Road, Central Bengaluru\xa0 | View All(7) OutletsMulticuisine₹2000 for two4.3', 'Flat 10% + 25% with Bank Offers'], ['Chianti', 'Multicuisine₹2000 for two', 'MG Road, Central Bengaluru\xa0 | View All(7) Outlets', 'ChiantiMG Road, Central Bengaluru\xa0 | View All(7) OutletsMulticuisine₹2000 for two4.3', 'Flat 10% + 25% with Bank Offers'], ['Toscano', 'Italian₹2000 for two', 'UB City, Central Bengaluru', 'ToscanoUB City, Central BengaluruItalian₹2000 for two5.0', '25% Off :Payeazy'], ['Toscano', 'Italian₹2000 for two', 'UB City, Central Bengaluru', 'ToscanoUB City, Central BengaluruItalian₹2000 for two5.0', '25% Off :Payeazy'], ['Pasta Street', 'Multicuisine₹2000 for two', 'Cunningham Road, Central Bengaluru\xa0 | View All(8) Outlets', 'Pasta StreetCunningham Road, Central Bengaluru\xa0 | View All(8) OutletsMulticuisine₹2000 for two4.6', '25% Off :Payeazy'], ['Pasta Street', 'Multicuisine₹2000 for two', 'Cunningham Road, Central Bengaluru\xa0 | View All(8) Outlets', 'Pasta StreetCunningham Road, Central Bengaluru\xa0 | View All(8) OutletsMulticuisine₹2000 for two4.6', '25% Off :Payeazy'], ['Cahoots Classic Bar House', 'Multicuisine₹4000 for two', 'Brigade Road, Central Bengaluru', 'Cahoots Classic Bar HouseBrigade Road, Central BengaluruMulticuisine₹4000 for two4.9', 'Flat 10% + 25% with Bank Offers'], ['Cahoots Classic Bar House', 'Multicuisine₹4000 for two', 'Brigade Road, Central Bengaluru', 'Cahoots Classic Bar HouseBrigade Road, Central BengaluruMulticuisine₹4000 for two4.9', 'Flat 10% + 25% with Bank Offers'], ['Full Peg', 'Finger Food, Cocktail Menu₹1000 for two', 'Nagarbhavi, West Bengaluru', 'Full PegNagarbhavi, West BengaluruFinger Food, Cocktail Menu₹1000 for two4.0', 'Flat 50% + 25% with Bank Offers'], ['Full Peg', 'Finger Food, Cocktail Menu₹1000 for two', 'Nagarbhavi, West Bengaluru', 'Full PegNagarbhavi, West BengaluruFinger Food, Cocktail Menu₹1000 for two4.0', 'Flat 50% + 25% with Bank Offers'], ['The Biere Club', 'Cocktail Menu, Multicuisine₹2000 for two', 'Lavelle Road, Central Bengaluru\xa0 | View All(2) Outlets', 'The Biere ClubLavelle Road, Central Bengaluru\xa0 | View All(2) OutletsCocktail Menu, Multicuisine₹2000 for two4.4', 'Flat 10% + 25% with Bank Offers'], ['The Biere Club', 'Cocktail Menu, Multicuisine₹2000 for two', 'Lavelle Road, Central Bengaluru\xa0 | View All(2) Outlets', 'The Biere ClubLavelle Road, Central Bengaluru\xa0 | View All(2) OutletsCocktail Menu, Multicuisine₹2000 for two4.4', 'Flat 10% + 25% with Bank Offers'], ['Citrus Cafe', 'Multicuisine₹1500 for two', 'Lemon Tree Premier, Ulsoor', 'Citrus CafeLemon Tree Premier, UlsoorMulticuisine₹1500 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Citrus Cafe', 'Multicuisine₹1500 for two', 'Lemon Tree Premier, Ulsoor', 'Citrus CafeLemon Tree Premier, UlsoorMulticuisine₹1500 for two4.0', 'Flat 10% + 25% with Bank Offers'], ['Ssaffron', 'Indian₹2500 for two', 'Shangri-La Bengaluru', 'SsaffronShangri-La BengaluruIndian₹2500 for two4.5', 'Flat 10% + 25% with Bank Offers'], ['Ssaffron', 'Indian₹2500 for two', 'Shangri-La Bengaluru', 'SsaffronShangri-La BengaluruIndian₹2500 for two4.5', 'Flat 10% + 25% with Bank Offers'], ['Chin Lung Resto Bar', 'Multicuisine₹2000 for two', 'Residency Road, Central Bengaluru\xa0 | View All(5) Outlets', 'Chin Lung Resto BarResidency Road, Central Bengaluru\xa0 | View All(5) OutletsMulticuisine₹2000 for two4.5', '

In [60]:
lines = [" ".join(map(str, row)) for row in data_lines]

for line in lines:
    print(line)
len(lines)

 Hamza Express - Since 1918 Multicuisine₹650 for two Shivajinagar, Central Bengaluru  Hamza Express - Since 1918Shivajinagar, Central BengaluruMulticuisine₹650 for two4.0 Flat 10% + 25% with Bank Offers
 Hamza Express - Since 1918 Multicuisine₹650 for two Shivajinagar, Central Bengaluru  Hamza Express - Since 1918Shivajinagar, Central BengaluruMulticuisine₹650 for two4.0 Flat 10% + 25% with Bank Offers
Savera Lassi Shop Beverages, Ice Cream₹2000 for two Shivajinagar, Central Bengaluru Savera Lassi ShopShivajinagar, Central BengaluruBeverages, Ice Cream₹2000 for two4.7 Flat 10% + 25% with Bank Offers
Savera Lassi Shop Beverages, Ice Cream₹2000 for two Shivajinagar, Central Bengaluru Savera Lassi ShopShivajinagar, Central BengaluruBeverages, Ice Cream₹2000 for two4.7 Flat 10% + 25% with Bank Offers
My Breakfast Multicuisine₹2000 for two Shivajinagar, Central Bengaluru My BreakfastShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0 Flat 10% + 25% with Bank Offers
My Breakfast Multicuisine₹2000 for two Shivajinagar, Central Bengaluru My BreakfastShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0 Flat 10% + 25% with Bank Offers
Nawabi Chai Cafe₹200 for two Shivajinagar, Central Bengaluru Nawabi ChaiShivajinagar, Central BengaluruCafe₹200 for two4.0 Flat 10% + 25% with Bank Offers
Nawabi Chai Cafe₹200 for two Shivajinagar, Central Bengaluru Nawabi ChaiShivajinagar, Central BengaluruCafe₹200 for two4.0 Flat 10% + 25% with Bank Offers
Tipsy Cafe Fast Food₹2000 for two Shivajinagar, Central Bengaluru Tipsy CafeShivajinagar, Central BengaluruFast Food₹2000 for two4.0 Flat 10% + 25% with Bank Offers
Tipsy Cafe Fast Food₹2000 for two Shivajinagar, Central Bengaluru Tipsy CafeShivajinagar, Central BengaluruFast Food₹2000 for two4.0 Flat 10% + 25% with Bank Offers
Shahi Restaurant Multicuisine₹2000 for two Shivajinagar, Central Bengaluru Shahi RestaurantShivajinagar, Central BengaluruMulticuisine₹2000 for two3.0 Flat 10% + 25% with Bank Offers
Shahi Restaurant Multicuisine₹2000 for two Shivajinagar, Central Bengaluru Shahi RestaurantShivajinagar, Central BengaluruMulticuisine₹2000 for two3.0 Flat 10% + 25% with Bank Offers
Main Lassi Shop Multicuisine₹2000 for two Shivajinagar, Central Bengaluru Main Lassi ShopShivajinagar, Central BengaluruMulticuisine₹2000 for two1.0 Flat 10% + 25% with Bank Offers
Main Lassi Shop Multicuisine₹2000 for two Shivajinagar, Central Bengaluru Main Lassi ShopShivajinagar, Central BengaluruMulticuisine₹2000 for two1.0 Flat 10% + 25% with Bank Offers
Maggi Baba Beverages₹200 for two Shivajinagar, Central Bengaluru Maggi BabaShivajinagar, Central BengaluruBeverages₹200 for two5.0 25% Off :Payeazy
Maggi Baba Beverages₹200 for two Shivajinagar, Central Bengaluru Maggi BabaShivajinagar, Central BengaluruBeverages₹200 for two5.0 25% Off :Payeazy
Romeo Cafe Multicuisine₹2000 for two Shivajinagar, Central Bengaluru Romeo CafeShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0 25% Off :Payeazy
Romeo Cafe Multicuisine₹2000 for two Shivajinagar, Central Bengaluru Romeo CafeShivajinagar, Central BengaluruMulticuisine₹2000 for two4.0 25% Off :Payeazy
CBD Central Bar District Multicuisine₹1200 for two MSR Nagar, Bengaluru CBD Central Bar DistrictMSR Nagar, BengaluruMulticuisine₹1200 for two4.8 Flat 25% + 25% with Bank Offers
CBD Central Bar District Multicuisine₹1200 for two MSR Nagar, Bengaluru CBD Central Bar DistrictMSR Nagar, BengaluruMulticuisine₹1200 for two4.8 Flat 25% + 25% with Bank Offers
Flo Multicuisine, Cocktail Menu₹2000 for two Church Street, Central Bengaluru FloChurch Street, Central BengaluruMulticuisine, Cocktail Menu₹2000 for two3.3 Flat 30% + 25% with Bank Offers
Flo Multicuisine, Cocktail Menu₹2000 for two Church Street, Central Bengaluru FloChurch Street, Central BengaluruMulticuisine, Cocktail Menu₹2000 for two3.3 Flat 30% + 25% with Bank Offers
ShakesBierre Cocktail Menu, Multicuisine₹2000 for two MG Road, Central Bengaluru ShakesBierreMG Road, Central BengaluruCocktail Menu, Multicuisine₹2000 for two4.4 Flat 10% + 25% with Bank Offers
ShakesBierre Cocktail Menu, Multicuisine₹2000 for two MG Road, Central Bengaluru ShakesBierreMG Road, Central BengaluruCocktail Menu, Multicuisine₹2000 for two4.4 Flat 10% + 25% with Bank Offers
Paradox Pub Chinese, Finger Food, Continental₹1200 for two Ashok Nagar, Bengaluru Paradox PubAshok Nagar, BengaluruChinese, Finger Food, Continental₹1200 for two5.0 Flat 30% + 25% with Bank Offers
Paradox Pub Chinese, Finger Food, Continental₹1200 for two Ashok Nagar, Bengaluru Paradox PubAshok Nagar, BengaluruChinese, Finger Food, Continental₹1200 for two5.0 Flat 30% + 25% with Bank Offers
Navya Samrat Restaurant Multicuisine₹2500 for two Infantry Road, Central Bengaluru Navya Samrat RestaurantInfantry Road, Central BengaluruMulticuisine₹2500 for two5.0 Flat 10% + 25% with Bank Offers
Navya Samrat Restaurant Multicuisine₹2500 for two Infantry Road, Central Bengaluru Navya Samrat RestaurantInfantry Road, Central BengaluruMulticuisine₹2500 for two5.0 Flat 10% + 25% with Bank Offers
Coastal Machali Co. Indian Coastal Cuisine, Chinese₹1500 for two Residency Road, Central Bengaluru Coastal Machali Co.Residency Road, Central BengaluruIndian Coastal Cuisine, Chinese₹1500 for two4.6 Flat 15% + 25% with Bank Offers
Coastal Machali Co. Indian Coastal Cuisine, Chinese₹1500 for two Residency Road, Central Bengaluru Coastal Machali Co.Residency Road, Central BengaluruIndian Coastal Cuisine, Chinese₹1500 for two4.6 Flat 15% + 25% with Bank Offers
SMOOR European₹2000 for two Lavelle Road, Central Bengaluru  | View All(9) Outlets SMOORLavelle Road, Central Bengaluru  | View All(9) OutletsEuropean₹2000 for two4.6 Flat 10% + 25% with Bank Offers
SMOOR European₹2000 for two Lavelle Road, Central Bengaluru  | View All(9) Outlets SMOORLavelle Road, Central Bengaluru  | View All(9) OutletsEuropean₹2000 for two4.6 Flat 10% + 25% with Bank Offers
Rolls On Wheels Chinese, Fast Food₹500 for two Cunningham Road, Central Bengaluru  | View All(19) Outlets Rolls On WheelsCunningham Road, Central Bengaluru  | View All(19) OutletsChinese, Fast Food₹500 for two4.0 Flat 15% + 25% with Bank Offers
Rolls On Wheels Chinese, Fast Food₹500 for two Cunningham Road, Central Bengaluru  | View All(19) Outlets Rolls On WheelsCunningham Road, Central Bengaluru  | View All(19) OutletsChinese, Fast Food₹500 for two4.0 Flat 15% + 25% with Bank Offers
Hatti Kaapi Multicuisine₹400 for two Infantry Road, Central Bengaluru  | View All(15) Outlets Hatti KaapiInfantry Road, Central Bengaluru  | View All(15) OutletsMulticuisine₹400 for two5.0 Flat 10% + 25% with Bank Offers
Hatti Kaapi Multicuisine₹400 for two Infantry Road, Central Bengaluru  | View All(15) Outlets Hatti KaapiInfantry Road, Central Bengaluru  | View All(15) OutletsMulticuisine₹400 for two5.0 Flat 10% + 25% with Bank Offers
Tiamo Italian, Mediterranean₹3000 for two Conrad Bengaluru TiamoConrad BengaluruItalian, Mediterranean₹3000 for two4.4 Flat 15% + 25% with Bank Offers
Tiamo Italian, Mediterranean₹3000 for two Conrad Bengaluru TiamoConrad BengaluruItalian, Mediterranean₹3000 for two4.4 Flat 15% + 25% with Bank Offers
Punjab Grill North Indian₹2000 for two Ashok Nagar, Bengaluru  | View All(8) Outlets Punjab GrillAshok Nagar, Bengaluru  | View All(8) OutletsNorth Indian₹2000 for two4.2 Flat 15% + 25% with Bank Offers
Punjab Grill North Indian₹2000 for two Ashok Nagar, Bengaluru  | View All(8) Outlets Punjab GrillAshok Nagar, Bengaluru  | View All(8) OutletsNorth Indian₹2000 for two4.2 Flat 15% + 25% with Bank Offers
Alchemy Fusion, Indian₹2500 for two The Chancery Pavilion, Bengaluru AlchemyThe Chancery Pavilion, BengaluruFusion, Indian₹2500 for two4.5 Flat 10% + 25% with Bank Offers
Alchemy Fusion, Indian₹2500 for two The Chancery Pavilion, Bengaluru AlchemyThe Chancery Pavilion, BengaluruFusion, Indian₹2500 for two4.5 Flat 10% + 25% with Bank Offers
JW Kitchen Multicuisine₹2500 for two JW Marriott, Bengaluru, Central Bengaluru JW KitchenJW Marriott, Bengaluru, Central BengaluruMulticuisine₹2500 for two4.4 Flat 25% + 25% with Bank Offers
JW Kitchen Multicuisine₹2500 for two JW Marriott, Bengaluru, Central Bengaluru JW KitchenJW Marriott, Bengaluru, Central BengaluruMulticuisine₹2500 for two4.4 Flat 25% + 25% with Bank Offers
Maayaa South Indian₹2000 for two The Courtyard by Sublime, Bengaluru MaayaaThe Courtyard by Sublime, BengaluruSouth Indian₹2000 for two4.4 Flat 15% + 25% with Bank Offers
Maayaa South Indian₹2000 for two The Courtyard by Sublime, Bengaluru MaayaaThe Courtyard by Sublime, BengaluruSouth Indian₹2000 for two4.4 Flat 15% + 25% with Bank Offers
Purpose Matcha + Coffee House Coffee₹550 for two Ashok Nagar, Bengaluru Purpose Matcha + Coffee HouseAshok Nagar, BengaluruCoffee₹550 for two4.7 25% Off :Payeazy
Purpose Matcha + Coffee House Coffee₹550 for two Ashok Nagar, Bengaluru Purpose Matcha + Coffee HouseAshok Nagar, BengaluruCoffee₹550 for two4.7 25% Off :Payeazy
Muro India Thai, Cantonese₹5000 for two Museum Road, Ashok Nagar, Bengaluru Muro IndiaMuseum Road, Ashok Nagar, BengaluruThai, Cantonese₹5000 for two4.5 25% Off :Payeazy
Muro India Thai, Cantonese₹5000 for two Museum Road, Ashok Nagar, Bengaluru Muro IndiaMuseum Road, Ashok Nagar, BengaluruThai, Cantonese₹5000 for two4.5 25% Off :Payeazy
Zed The Baker Italian, French₹2000 for two Church Street, Central Bengaluru  | View All(5) Outlets Zed The BakerChurch Street, Central Bengaluru  | View All(5) OutletsItalian, French₹2000 for two4.5 Flat 10% + 25% with Bank Offers
Zed The Baker Italian, French₹2000 for two Church Street, Central Bengaluru  | View All(5) Outlets Zed The BakerChurch Street, Central Bengaluru  | View All(5) OutletsItalian, French₹2000 for two4.5 Flat 10% + 25% with Bank Offers
Yauatcha Multicuisine₹3000 for two 1MG Road Mall, MG Road Yauatcha1MG Road Mall, MG RoadMulticuisine₹3000 for two4.6 25% Off :Payeazy
Yauatcha Multicuisine₹3000 for two 1MG Road Mall, MG Road Yauatcha1MG Road Mall, MG RoadMulticuisine₹3000 for two4.6 25% Off :Payeazy
Spice It Multicuisine₹2000 for two Ibis Hotel, Richmond Road  | View All(4) Outlets Spice ItIbis Hotel, Richmond Road  | View All(4) OutletsMulticuisine₹2000 for two3.5 Flat 30% + 25% with Bank Offers
Spice It Multicuisine₹2000 for two Ibis Hotel, Richmond Road  | View All(4) Outlets Spice ItIbis Hotel, Richmond Road  | View All(4) OutletsMulticuisine₹2000 for two3.5 Flat 30% + 25% with Bank Offers
Scottish Pub Multicuisine₹2000 for two St. Marks Road, Central Bengaluru Scottish PubSt. Marks Road, Central BengaluruMulticuisine₹2000 for two4.9 Flat 10% + 25% with Bank Offers
Scottish Pub Multicuisine₹2000 for two St. Marks Road, Central Bengaluru Scottish PubSt. Marks Road, Central BengaluruMulticuisine₹2000 for two4.9 Flat 10% + 25% with Bank Offers
Monsoon Multicuisine₹2000 for two The Park, Bengaluru MonsoonThe Park, BengaluruMulticuisine₹2000 for two3.9 Flat 25% + 25% with Bank Offers
Monsoon Multicuisine₹2000 for two The Park, Bengaluru MonsoonThe Park, BengaluruMulticuisine₹2000 for two3.9 Flat 25% + 25% with Bank Offers
Church Street Social Multicuisine₹2000 for two Church Street, Central Bengaluru  | View All(12) Outlets Church Street SocialChurch Street, Central Bengaluru  | View All(12) OutletsMulticuisine₹2000 for two4.2 25% Off :Payeazy
Church Street Social Multicuisine₹2000 for two Church Street, Central Bengaluru  | View All(12) Outlets Church Street SocialChurch Street, Central Bengaluru  | View All(12) OutletsMulticuisine₹2000 for two4.2 25% Off :Payeazy
Toca Terrace Multicuisine₹2000 for two Brigade Road, Central Bengaluru Toca TerraceBrigade Road, Central BengaluruMulticuisine₹2000 for two4.0 25% Off :Payeazy
Toca Terrace Multicuisine₹2000 for two Brigade Road, Central Bengaluru Toca TerraceBrigade Road, Central BengaluruMulticuisine₹2000 for two4.0 25% Off :Payeazy
SkyDeck By Sherlock's Multicuisine₹2000 for two MG Road, Central Bengaluru SkyDeck By Sherlock'sMG Road, Central BengaluruMulticuisine₹2000 for two4.1 Flat 15% + 25% with Bank Offers
SkyDeck By Sherlock's Multicuisine₹2000 for two MG Road, Central Bengaluru SkyDeck By Sherlock'sMG Road, Central BengaluruMulticuisine₹2000 for two4.1 Flat 15% + 25% with Bank Offers
Ishaara Multicuisine₹1800 for two St. Marks Road, Central Bengaluru IshaaraSt. Marks Road, Central BengaluruMulticuisine₹1800 for two5.0 Flat 10% + 25% with Bank Offers
Ishaara Multicuisine₹1800 for two St. Marks Road, Central Bengaluru IshaaraSt. Marks Road, Central BengaluruMulticuisine₹1800 for two5.0 Flat 10% + 25% with Bank Offers
Ta'aam Arabian, North Indian₹600 for two Cunningham Road, Central Bengaluru Ta'aamCunningham Road, Central BengaluruArabian, North Indian₹600 for two5.0 25% Off :Payeazy
Ta'aam Arabian, North Indian₹600 for two Cunningham Road, Central Bengaluru Ta'aamCunningham Road, Central BengaluruArabian, North Indian₹600 for two5.0 25% Off :Payeazy
Cafe Noir European₹1000 for two UB City, Central Bengaluru  | View All(6) Outlets Cafe NoirUB City, Central Bengaluru  | View All(6) OutletsEuropean₹1000 for two4.4 Flat 10% + 25% with Bank Offers
Cafe Noir European₹1000 for two UB City, Central Bengaluru  | View All(6) Outlets Cafe NoirUB City, Central Bengaluru  | View All(6) OutletsEuropean₹1000 for two4.4 Flat 10% + 25% with Bank Offers
Sable Cafe Desserts, European, Cafe₹600 for two Indiranagar, East Bengaluru Sable CafeIndiranagar, East BengaluruDesserts, European, Cafe₹600 for two4.0 Flat 15% + 25% with Bank Offers
Sable Cafe Desserts, European, Cafe₹600 for two Indiranagar, East Bengaluru Sable CafeIndiranagar, East BengaluruDesserts, European, Cafe₹600 for two4.0 Flat 15% + 25% with Bank Offers
New Kudla Family Restaurant North Indian, Chinese₹2000 for two MG Road, Central Bengaluru New Kudla Family RestaurantMG Road, Central BengaluruNorth Indian, Chinese₹2000 for two4.0 Flat 50% + 25% with Bank Offers
New Kudla Family Restaurant North Indian, Chinese₹2000 for two MG Road, Central Bengaluru New Kudla Family RestaurantMG Road, Central BengaluruNorth Indian, Chinese₹2000 for two4.0 Flat 50% + 25% with Bank Offers
Monarch Cafe Multicuisine₹2000 for two Infantry Road, Central Bengaluru Monarch CafeInfantry Road, Central BengaluruMulticuisine₹2000 for two4.0 25% Off :Payeazy
Monarch Cafe Multicuisine₹2000 for two Infantry Road, Central Bengaluru Monarch CafeInfantry Road, Central BengaluruMulticuisine₹2000 for two4.0 25% Off :Payeazy
Cafe Adams European₹2000 for two Shivajinagar, Central Bengaluru Cafe AdamsShivajinagar, Central BengaluruEuropean₹2000 for two4.0 25% Off :Payeazy
Cafe Adams European₹2000 for two Shivajinagar, Central Bengaluru Cafe AdamsShivajinagar, Central BengaluruEuropean₹2000 for two4.0 25% Off :Payeazy
Atlas World Cafe Multicuisine₹2000 for two Vividus Hotel, Bengaluru Atlas World CafeVividus Hotel, BengaluruMulticuisine₹2000 for two4.2 Flat 15% + 25% with Bank Offers
Atlas World Cafe Multicuisine₹2000 for two Vividus Hotel, Bengaluru Atlas World CafeVividus Hotel, BengaluruMulticuisine₹2000 for two4.2 Flat 15% + 25% with Bank Offers
Chianti Multicuisine₹2000 for two MG Road, Central Bengaluru  | View All(7) Outlets ChiantiMG Road, Central Bengaluru  | View All(7) OutletsMulticuisine₹2000 for two4.3 Flat 10% + 25% with Bank Offers
Chianti Multicuisine₹2000 for two MG Road, Central Bengaluru  | View All(7) Outlets ChiantiMG Road, Central Bengaluru  | View All(7) OutletsMulticuisine₹2000 for two4.3 Flat 10% + 25% with Bank Offers
Toscano Italian₹2000 for two UB City, Central Bengaluru ToscanoUB City, Central BengaluruItalian₹2000 for two5.0 25% Off :Payeazy
Toscano Italian₹2000 for two UB City, Central Bengaluru ToscanoUB City, Central BengaluruItalian₹2000 for two5.0 25% Off :Payeazy
Pasta Street Multicuisine₹2000 for two Cunningham Road, Central Bengaluru  | View All(8) Outlets Pasta StreetCunningham Road, Central Bengaluru  | View All(8) OutletsMulticuisine₹2000 for two4.6 25% Off :Payeazy
Pasta Street Multicuisine₹2000 for two Cunningham Road, Central Bengaluru  | View All(8) Outlets Pasta StreetCunningham Road, Central Bengaluru  | View All(8) OutletsMulticuisine₹2000 for two4.6 25% Off :Payeazy
Cahoots Classic Bar House Multicuisine₹4000 for two Brigade Road, Central Bengaluru Cahoots Classic Bar HouseBrigade Road, Central BengaluruMulticuisine₹4000 for two4.9 Flat 10% + 25% with Bank Offers
Cahoots Classic Bar House Multicuisine₹4000 for two Brigade Road, Central Bengaluru Cahoots Classic Bar HouseBrigade Road, Central BengaluruMulticuisine₹4000 for two4.9 Flat 10% + 25% with Bank Offers
Full Peg Finger Food, Cocktail Menu₹1000 for two Nagarbhavi, West Bengaluru Full PegNagarbhavi, West BengaluruFinger Food, Cocktail Menu₹1000 for two4.0 Flat 50% + 25% with Bank Offers
Full Peg Finger Food, Cocktail Menu₹1000 for two Nagarbhavi, West Bengaluru Full PegNagarbhavi, West BengaluruFinger Food, Cocktail Menu₹1000 for two4.0 Flat 50% + 25% with Bank Offers
The Biere Club Cocktail Menu, Multicuisine₹2000 for two Lavelle Road, Central Bengaluru  | View All(2) Outlets The Biere ClubLavelle Road, Central Bengaluru  | View All(2) OutletsCocktail Menu, Multicuisine₹2000 for two4.4 Flat 10% + 25% with Bank Offers
The Biere Club Cocktail Menu, Multicuisine₹2000 for two Lavelle Road, Central Bengaluru  | View All(2) Outlets The Biere ClubLavelle Road, Central Bengaluru  | View All(2) OutletsCocktail Menu, Multicuisine₹2000 for two4.4 Flat 10% + 25% with Bank Offers
Citrus Cafe Multicuisine₹1500 for two Lemon Tree Premier, Ulsoor Citrus CafeLemon Tree Premier, UlsoorMulticuisine₹1500 for two4.0 Flat 10% + 25% with Bank Offers
Citrus Cafe Multicuisine₹1500 for two Lemon Tree Premier, Ulsoor Citrus CafeLemon Tree Premier, UlsoorMulticuisine₹1500 for two4.0 Flat 10% + 25% with Bank Offers
Ssaffron Indian₹2500 for two Shangri-La Bengaluru SsaffronShangri-La BengaluruIndian₹2500 for two4.5 Flat 10% + 25% with Bank Offers
Ssaffron Indian₹2500 for two Shangri-La Bengaluru SsaffronShangri-La BengaluruIndian₹2500 for two4.5 Flat 10% + 25% with Bank Offers
Chin Lung Resto Bar Multicuisine₹2000 for two Residency Road, Central Bengaluru  | View All(5) Outlets Chin Lung Resto BarResidency Road, Central Bengaluru  | View All(5) OutletsMulticuisine₹2000 for two4.5 25% Off :Payeazy
Chin Lung Resto Bar Multicuisine₹2000 for two Residency Road, Central Bengaluru  | View All(5) Outlets Chin Lung Resto BarResidency Road, Central Bengaluru  | View All(5) OutletsMulticuisine₹2000 for two4.5 25% Off :Payeazy
Altitude Kitchen & Bar Cocktail Menu, Multicuisine₹2000 for two Basaveshwara Nagar, West Bengaluru Altitude Kitchen & BarBasaveshwara Nagar, West BengaluruCocktail Menu, Multicuisine₹2000 for two3.4 Flat 20% + 25% with Bank Offers
Altitude Kitchen & Bar Cocktail Menu, Multicuisine₹2000 for two Basaveshwara Nagar, West Bengaluru Altitude Kitchen & BarBasaveshwara Nagar, West BengaluruCocktail Menu, Multicuisine₹2000 for two3.4 Flat 20% + 25% with Bank Offers
Pixi Continental₹1600 for two Ashok Nagar, Bengaluru PixiAshok Nagar, BengaluruContinental₹1600 for two5.0 25% Off :Payeazy
Pixi Continental₹1600 for two Ashok Nagar, Bengaluru PixiAshok Nagar, BengaluruContinental₹1600 for two5.0 25% Off :Payeazy
Kari Theory Cocktail Menu, Multicuisine₹2500 for two Radisson Bengaluru City Center Kari TheoryRadisson Bengaluru City CenterCocktail Menu, Multicuisine₹2500 for two3.9 Flat 20% + 25% with Bank Offers
Kari Theory Cocktail Menu, Multicuisine₹2500 for two Radisson Bengaluru City Center Kari TheoryRadisson Bengaluru City CenterCocktail Menu, Multicuisine₹2500 for two3.9 Flat 20% + 25% with Bank Offers
B Cafe Multicuisine₹2500 for two Shangri-La Bengaluru B CafeShangri-La BengaluruMulticuisine₹2500 for two4.6 Flat 10% + 25% with Bank Offers
B Cafe Multicuisine₹2500 for two Shangri-La Bengaluru B CafeShangri-La BengaluruMulticuisine₹2500 for two4.6 Flat 10% + 25% with Bank Offers
Zest Multicuisine₹2100 for two Southern Star, Bengaluru ZestSouthern Star, BengaluruMulticuisine₹2100 for two4.3 Flat 15% + 25% with Bank Offers

2400

In [61]:
df[['Cuisine','cost_of_two']] = df['Cost_of_two'].str.extract(r'(.*?)(₹.*)')
df['cost_of_two'] = df['cost_of_two'].str.extract(r'(\d+)').astype('int')
df

,Restaurants_Name,Cost_of_two,Areas,Reatings,Discounts,Cuisine,cost_of_two
0,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650
1,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650
2,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000
3,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000
4,My Breakfast,Multicuisine₹2000 for two,"Shivajinagar, Central Bengaluru","My BreakfastShivajinagar, Central BengaluruMul...",Flat 10% + 25% with Bank Offers,Multicuisine,2000
...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine₹2500 for two,"Yelahanka, North Bengaluru","The Brew Factory Sahakara NagarYelahanka, Nort...",25% Off :Payeazy,Multicuisine,2500
2396,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000
2397,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000
2398,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000
2399,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000

In [62]:
df['ratings'] = df['Reatings'].str.extract(r'(\d\.\d)$').astype('float')
df

,Restaurants_Name,Cost_of_two,Areas,Reatings,Discounts,Cuisine,cost_of_two,ratings
0,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650,4.0
1,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650,4.0
2,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000,4.7
3,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000,4.7
4,My Breakfast,Multicuisine₹2000 for two,"Shivajinagar, Central Bengaluru","My BreakfastShivajinagar, Central BengaluruMul...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.0
...,...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine₹2500 for two,"Yelahanka, North Bengaluru","The Brew Factory Sahakara NagarYelahanka, Nort...",25% Off :Payeazy,Multicuisine,2500,5.0
2396,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000,1.8
2397,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000,1.8
2398,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.7
2399,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.7

In [63]:
df[['area', 'region']] = df['Areas'].str.extract(r"([^'\n]+?)(?:,\s*|\s+)((?:Central|West|South|North|East)?\s*Bengaluru)")

In [64]:
df

,Restaurants_Name,Cost_of_two,Areas,Reatings,Discounts,Cuisine,cost_of_two,ratings,area,region
0,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650,4.0,Shivajinagar,Central Bengaluru
1,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650,4.0,Shivajinagar,Central Bengaluru
2,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000,4.7,Shivajinagar,Central Bengaluru
3,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000,4.7,Shivajinagar,Central Bengaluru
4,My Breakfast,Multicuisine₹2000 for two,"Shivajinagar, Central Bengaluru","My BreakfastShivajinagar, Central BengaluruMul...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.0,Shivajinagar,Central Bengaluru
...,...,...,...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine₹2500 for two,"Yelahanka, North Bengaluru","The Brew Factory Sahakara NagarYelahanka, Nort...",25% Off :Payeazy,Multicuisine,2500,5.0,Yelahanka,North Bengaluru
2396,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000,1.8,Yelahanka,North Bengaluru
2397,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000,1.8,Yelahanka,North Bengaluru
2398,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.7,Whitefield,East Bengaluru
2399,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.7,Whitefield,East Bengaluru

In [65]:
def extract_discounts(offer):
    return re.findall(r'(\d+)%', str(offer))

df['Discount'] = df['Discounts'].apply(extract_discounts)
df['Discount'].apply(pd.Series)

       0    1
0     10   25
1     10   25
2     10   25
3     10   25
4     10   25
...   ..  ...
2395  25  NaN
2396  15   25
2397  15   25
2398  10   25
2399  10   25

[2400 rows x 2 columns]

In [66]:
df['Discount'] = df['Discount'].apply(lambda x: sum(map(int, x)) if isinstance(x, list) else 0)
df['Discount'].head()

0    35
1    35
2    35
3    35
4    35
Name: Discount, dtype: int64

In [67]:
df

,Restaurants_Name,Cost_of_two,Areas,Reatings,Discounts,Cuisine,cost_of_two,ratings,area,region,Discount
0,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650,4.0,Shivajinagar,Central Bengaluru,35
1,Hamza Express - Since 1918,Multicuisine₹650 for two,"Shivajinagar, Central Bengaluru","Hamza Express - Since 1918Shivajinagar, Centr...",Flat 10% + 25% with Bank Offers,Multicuisine,650,4.0,Shivajinagar,Central Bengaluru,35
2,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000,4.7,Shivajinagar,Central Bengaluru,35
3,Savera Lassi Shop,"Beverages, Ice Cream₹2000 for two","Shivajinagar, Central Bengaluru","Savera Lassi ShopShivajinagar, Central Bengalu...",Flat 10% + 25% with Bank Offers,"Beverages, Ice Cream",2000,4.7,Shivajinagar,Central Bengaluru,35
4,My Breakfast,Multicuisine₹2000 for two,"Shivajinagar, Central Bengaluru","My BreakfastShivajinagar, Central BengaluruMul...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.0,Shivajinagar,Central Bengaluru,35
...,...,...,...,...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine₹2500 for two,"Yelahanka, North Bengaluru","The Brew Factory Sahakara NagarYelahanka, Nort...",25% Off :Payeazy,Multicuisine,2500,5.0,Yelahanka,North Bengaluru,25
2396,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000,1.8,Yelahanka,North Bengaluru,40
2397,Hyderabadi Bawarchi,Biryani₹2000 for two,"Yelahanka, North Bengaluru","Hyderabadi BawarchiYelahanka, North BengaluruB...",Flat 15% + 25% with Bank Offers,Biryani,2000,1.8,Yelahanka,North Bengaluru,40
2398,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.7,Whitefield,East Bengaluru,35
2399,Celeb's RestoBar,Multicuisine₹2000 for two,"Whitefield, East Bengaluru","Celeb's RestoBarWhitefield, East BengaluruMult...",Flat 10% + 25% with Bank Offers,Multicuisine,2000,4.7,Whitefield,East Bengaluru,35

# Droping cost_of_two, Areas, Ratings, Discounts

In [68]:
df.drop(columns = ['Cost_of_two','Areas','Reatings','Discounts'], axis = 1)

,Restaurants_Name,Cuisine,cost_of_two,ratings,area,region,Discount
0,Hamza Express - Since 1918,Multicuisine,650,4.0,Shivajinagar,Central Bengaluru,35
1,Hamza Express - Since 1918,Multicuisine,650,4.0,Shivajinagar,Central Bengaluru,35
2,Savera Lassi Shop,"Beverages, Ice Cream",2000,4.7,Shivajinagar,Central Bengaluru,35
3,Savera Lassi Shop,"Beverages, Ice Cream",2000,4.7,Shivajinagar,Central Bengaluru,35
4,My Breakfast,Multicuisine,2000,4.0,Shivajinagar,Central Bengaluru,35
...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine,2500,5.0,Yelahanka,North Bengaluru,25
2396,Hyderabadi Bawarchi,Biryani,2000,1.8,Yelahanka,North Bengaluru,40
2397,Hyderabadi Bawarchi,Biryani,2000,1.8,Yelahanka,North Bengaluru,40
2398,Celeb's RestoBar,Multicuisine,2000,4.7,Whitefield,East Bengaluru,35
2399,Celeb's RestoBar,Multicuisine,2000,4.7,Whitefield,East Bengaluru,35

In [69]:
desired_order = ['Restaurants_Name', 'Cuisine', 'area', 'region', 'Discount', 'cost_of_two', 'ratings']
df = df[desired_order]

In [70]:
df

,Restaurants_Name,Cuisine,area,region,Discount,cost_of_two,ratings
0,Hamza Express - Since 1918,Multicuisine,Shivajinagar,Central Bengaluru,35,650,4.0
1,Hamza Express - Since 1918,Multicuisine,Shivajinagar,Central Bengaluru,35,650,4.0
2,Savera Lassi Shop,"Beverages, Ice Cream",Shivajinagar,Central Bengaluru,35,2000,4.7
3,Savera Lassi Shop,"Beverages, Ice Cream",Shivajinagar,Central Bengaluru,35,2000,4.7
4,My Breakfast,Multicuisine,Shivajinagar,Central Bengaluru,35,2000,4.0
...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine,Yelahanka,North Bengaluru,25,2500,5.0
2396,Hyderabadi Bawarchi,Biryani,Yelahanka,North Bengaluru,40,2000,1.8
2397,Hyderabadi Bawarchi,Biryani,Yelahanka,North Bengaluru,40,2000,1.8
2398,Celeb's RestoBar,Multicuisine,Whitefield,East Bengaluru,35,2000,4.7
2399,Celeb's RestoBar,Multicuisine,Whitefield,East Bengaluru,35,2000,4.7

In [71]:
df.to_csv('eazydiner_cleaned_data.csv', index = False)

In [72]:
df = pd.read_csv('eazydiner_cleaned_data.csv')
df

,Restaurants_Name,Cuisine,area,region,Discount,cost_of_two,ratings
0,Hamza Express - Since 1918,Multicuisine,Shivajinagar,Central Bengaluru,35,650,4.0
1,Hamza Express - Since 1918,Multicuisine,Shivajinagar,Central Bengaluru,35,650,4.0
2,Savera Lassi Shop,"Beverages, Ice Cream",Shivajinagar,Central Bengaluru,35,2000,4.7
3,Savera Lassi Shop,"Beverages, Ice Cream",Shivajinagar,Central Bengaluru,35,2000,4.7
4,My Breakfast,Multicuisine,Shivajinagar,Central Bengaluru,35,2000,4.0
...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine,Yelahanka,North Bengaluru,25,2500,5.0
2396,Hyderabadi Bawarchi,Biryani,Yelahanka,North Bengaluru,40,2000,1.8
2397,Hyderabadi Bawarchi,Biryani,Yelahanka,North Bengaluru,40,2000,1.8
2398,Celeb's RestoBar,Multicuisine,Whitefield,East Bengaluru,35,2000,4.7
2399,Celeb's RestoBar,Multicuisine,Whitefield,East Bengaluru,35,2000,4.7

In [73]:
df

,Restaurants_Name,Cuisine,area,region,Discount,cost_of_two,ratings
0,Hamza Express - Since 1918,Multicuisine,Shivajinagar,Central Bengaluru,35,650,4.0
1,Hamza Express - Since 1918,Multicuisine,Shivajinagar,Central Bengaluru,35,650,4.0
2,Savera Lassi Shop,"Beverages, Ice Cream",Shivajinagar,Central Bengaluru,35,2000,4.7
3,Savera Lassi Shop,"Beverages, Ice Cream",Shivajinagar,Central Bengaluru,35,2000,4.7
4,My Breakfast,Multicuisine,Shivajinagar,Central Bengaluru,35,2000,4.0
...,...,...,...,...,...,...,...
2395,The Brew Factory Sahakara Nagar,Multicuisine,Yelahanka,North Bengaluru,25,2500,5.0
2396,Hyderabadi Bawarchi,Biryani,Yelahanka,North Bengaluru,40,2000,1.8
2397,Hyderabadi Bawarchi,Biryani,Yelahanka,North Bengaluru,40,2000,1.8
2398,Celeb's RestoBar,Multicuisine,Whitefield,East Bengaluru,35,2000,4.7
2399,Celeb's RestoBar,Multicuisine,Whitefield,East Bengaluru,35,2000,4.7